In [ ]:
## Reference Source: https://www.askpython.com/python/examples/principal-component-analysis
## Not for this program, but to understand PCA. 

import pandas as pd
import numpy as np
#Generate a dummy dataset.
X = np.random.randint(10,50,100).reshape(20,5) 
print(X)


[[47 11 22 24 23]
 [20 24 45 16 44]
 [20 33 10 44 17]
 [33 46 47 31 17]
 [44 15 42 35 29]
 [23 15 17 30 20]
 [35 16 20 32 49]
 [48 15 29 37 39]
 [15 33 32 26 14]
 [36 23 31 29 35]
 [40 38 22 36 36]
 [35 44 19 48 17]
 [11 26 47 24 46]
 [41 40 48 48 27]
 [45 32 12 18 44]
 [33 24 15 14 10]
 [18 26 25 23 11]
 [43 45 33 12 29]
 [33 47 31 13 47]
 [28 42 32 49 11]]


In [ ]:
# mean Centering the data  
X_meaned = X - np.mean(X , axis = 0)
print(X_meaned)

[[ 14.6  -18.75  -6.95  -5.45  -5.25]
 [-12.4   -5.75  16.05 -13.45  15.75]
 [-12.4    3.25 -18.95  14.55 -11.25]
 [  0.6   16.25  18.05   1.55 -11.25]
 [ 11.6  -14.75  13.05   5.55   0.75]
 [ -9.4  -14.75 -11.95   0.55  -8.25]
 [  2.6  -13.75  -8.95   2.55  20.75]
 [ 15.6  -14.75   0.05   7.55  10.75]
 [-17.4    3.25   3.05  -3.45 -14.25]
 [  3.6   -6.75   2.05  -0.45   6.75]
 [  7.6    8.25  -6.95   6.55   7.75]
 [  2.6   14.25  -9.95  18.55 -11.25]
 [-21.4   -3.75  18.05  -5.45  17.75]
 [  8.6   10.25  19.05  18.55  -1.25]
 [ 12.6    2.25 -16.95 -11.45  15.75]
 [  0.6   -5.75 -13.95 -15.45 -18.25]
 [-14.4   -3.75  -3.95  -6.45 -17.25]
 [ 10.6   15.25   4.05 -17.45   0.75]
 [  0.6   17.25   2.05 -16.45  18.75]
 [ -4.4   12.25   3.05  19.55 -17.25]]


In [ ]:
# calculating the covariance matrix of the mean-centered data.
cov_mat = np.cov(X_meaned , rowvar = False)
print(cov_mat)

[[126.56842105  -7.73684211 -15.50526316   9.6         32.15789474]
 [ -7.73684211 141.03947368  25.88157895  16.48684211 -25.46052632]
 [-15.50526316  25.88157895 145.31315789   1.12894737  31.17105263]
 [  9.6         16.48684211   1.12894737 140.05       -47.80263158]
 [ 32.15789474 -25.46052632  31.17105263 -47.80263158 180.19736842]]


In [ ]:
#Calculating Eigenvalues and Eigenvectors of the covariance matrix
eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)
print("Eigen Values are", eigen_values)
print("Eigen Vectors are", eigen_vectors)

Eigen Values are [ 75.39958405 111.87193312 140.56434279 174.77677497 230.55578612]
Eigen Vectors are [[-5.24185737e-01  2.51914418e-01  7.49417475e-01 -2.42554306e-01
   2.03246884e-01]
 [ 2.15645543e-01  7.19331345e-01  1.70687323e-01  5.72278444e-01
  -2.81820221e-01]
 [-4.44941979e-01 -4.23384041e-01  3.56492757e-02  7.70762475e-01
   1.65610766e-01]
 [ 4.31759717e-01 -4.89742275e-01  6.05371670e-01  4.94670849e-02
  -4.52564028e-01]
 [ 5.42527875e-01 -1.84435354e-06  2.03699671e-01  1.30931305e-01
   8.04379849e-01]]


In [ ]:
#sort the eigenvalues in descending order
sorted_index = np.argsort(eigen_values)[::-1]
print("The Sorted Eigen Values are", sorted_index)
sorted_eigenvalue = eigen_values[sorted_index]
#similarly sort the eigenvectors 
sorted_eigenvectors = eigen_vectors[:,sorted_index]
print("The Sorted Eigen Vectors are", sorted_eigenvectors)

The Sorted Eigen Values are [4 3 2 1 0]
The Sorted Eigen Vectors are [[ 2.03246884e-01 -2.42554306e-01  7.49417475e-01  2.51914418e-01
  -5.24185737e-01]
 [-2.81820221e-01  5.72278444e-01  1.70687323e-01  7.19331345e-01
   2.15645543e-01]
 [ 1.65610766e-01  7.70762475e-01  3.56492757e-02 -4.23384041e-01
  -4.44941979e-01]
 [-4.52564028e-01  4.94670849e-02  6.05371670e-01 -4.89742275e-01
   4.31759717e-01]
 [ 8.04379849e-01  1.30931305e-01  2.03699671e-01 -1.84435354e-06
   5.42527875e-01]]


In [ ]:
# select the first n eigenvectors, n is desired dimension
# of our final reduced data.
 
n_components = 2 #you can select any number of components.
eigenvector_subset = sorted_eigenvectors[:,0:n_components]
print(eigenvector_subset)

[[ 0.20324688 -0.24255431]
 [-0.28182022  0.57227844]
 [ 0.16561077  0.77076247]
 [-0.45256403  0.04946708]
 [ 0.80437985  0.13093131]]


In [ ]:
#Transform the data 
X_reduced = np.dot(eigenvector_subset.transpose(),X.transpose()).transpose()
print(X_reduced)

[[ 17.73521781  16.05041502]
 [ 32.90542575  50.12035869]
 [ -9.81738176  26.1441112 ]
 [  1.17209556  58.30566446]
 [ 19.15848638  35.81216697]
 [  5.77343417  20.21102835]
 [ 30.84929643  24.08088457]
 [ 24.95720439  26.2302848 ]
 [ -1.45716637  43.03045573]
 [ 20.99789438  34.34122706]
 [ 13.72951337  35.49552513]
 [-10.18846015  35.93559011]
 [ 28.83203236  55.64702857]
 [  5.00481274  55.85257532]
 [ 29.36175275  23.2985011 ]
 [  4.13552545  19.29367992]
 [ -1.089407    32.36031121]
 [ 19.41910863  45.14846936]
 [ 30.51805108  49.58327494]
 [-14.17345106  45.77270479]]
